Linters
MahdiAghaali/Hello-Microvese pull request #1
Opened 2022-08-16 16:18 UTC by MahdiAghaali

I this Milestone I did:

1. Update Readme.md
2. Add index.html
3. Initialize package.json
4. Add Index.css file for markup
5. Ignore node_modules and test.md
6. Setup Linters

2022-08-16 16:38 UTC, HAMMAS-SALEEM requested changes
# First of all Welcome to Microverse :tada: :bouquet:
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/93039359/178569876-9fcda5e8-6819-4569-95ee-acb393903a05.jpg)

### Hey @MahdiAghaali :wave:

### Highlights :1st_place_medal:
 
:heavy_check_mark: Meaningful commits
:heavy_check_mark: Added .gitignore
:heavy_check_mark: Following Github Flow

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional Suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification. Otherwise reach out to me on slack which is more fast. You can reach out to me on slack by searching my name in **full-time-students** channel :+1:

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 16:38 UTC, HAMMAS-SALEEM commented on README.md
> -
- [ ] Why did you remove **Acknowledge** and **License** section from your readme file. :thinking: Please add them in your Readme file because your Readme file is the documentation file so please take it seriously :blush:

2022-08-16 16:38 UTC, HAMMAS-SALEEM commented on README.md
> +> Getting started with Linters and Git
- [ ] Please add a short summary about your project. The summary which you have added is not telling what your project is about :thinking: You can see this [readme sample](https://github.com/HAMMAS-SALEEM/Hello-Microverse/blob/refactor-authentication/README.md) to get an idea. :+1:

2022-08-16 16:38 UTC, HAMMAS-SALEEM commented on README.md
> -This project is [MIT](./LICENSE) licensed.
### Your MIT.md file
![MIT](https://user-images.githubusercontent.com/93039359/184926415-8afd8e50-667b-4fb5-a65e-b03e355afd4f.png)

- [ ] Please add your name, current year, app type in your MIT.md file. :blush: because this is your license file please take it seriously :blush:

2022-08-16 16:38 UTC, HAMMAS-SALEEM commented on README.md
![pr-title](https://user-images.githubusercontent.com/93039359/184932350-0fdf3993-3307-4ab7-9704-9d1373a8a0c0.png)


- [ ] Your PR has a title that is not so descriptive enough. Because **Linters** is not describing what are you doing in the project. PR title fully describes what is happening in this branch. You could use **Setup Hello Microverse Project** for your PR title. :+1:

2022-08-16 16:38 UTC, HAMMAS-SALEEM commented on README.md
### Branch name
![pr-title (copy)](https://user-images.githubusercontent.com/93039359/184932572-68f09c1d-03fc-455a-9c3b-872ab87ae839.png)

- [ ] Your branch name is not descriptive enough. You are using **Linters**, you can use  **feature/setup-hello-microverse** or **feature/initialize-hello-microverse** :+1:

2022-08-17 09:32 UTC, closed without merging

2022-08-17 09:33 UTC, MahdiAghaali commented on README.md
I changed the branch name, and doing so closed this PR
![Branch](https://user-images.githubusercontent.com/93377744/185085945-50db2f3e-f247-4fe2-9edf-f06b2ee5291e.PNG)

2022-08-17 10:11 UTC, sja-thedude commented on README.md
> -
Implemented 👍

2022-08-17 10:11 UTC, sja-thedude commented on README.md
> +> Getting started with Linters and Git
Implemented 👍

2022-08-17 10:12 UTC, sja-thedude commented on README.md
> -This project is [MIT](./LICENSE) licensed.
Implemented 👍

2022-08-17 10:13 UTC, sja-thedude commented on README.md
Implemented 👍

2022-08-17 10:13 UTC, sja-thedude commented on README.md
Implemented 👍